### ISSUE TITLE
Updates to Domain: Groundwater Adjustment Exception

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#10]
Typo in the Domain [Groundwater Adjustment Exception]
![Image](https://user-images.githubusercontent.com/55856222/189428295-bc25e93b-2141-4986-9f9b-13a0e8670918.png)

This Domain also doesn't seem to be assigned to the field [SensorAdjustmentException]
![Image](https://user-images.githubusercontent.com/55856222/189428501-291365b1-0685-4583-b9f8-44fa2a7ee327.png)

**Comment by mmannion** [comment]
Updated several commits ago, and subsequently made copious changes (OS auth for `sde`, `hydro`) in order to test. Don't know specific commit number at this point, but verified in latest test deployment that this is fixed.
