### ISSUE TITLE
Desiccant Field Names

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#107]
Based on the initial feedback it was proposed to update the Desiccant Status questions. More discussion is needed

- Change “…Stage status” to “…transducer status”
- Change “… groundwater status” to “…transducer  status” 

To do:
- [x] @mmannion Combine `LocationVisit.DesiccantStage` / `.DesiccantGroundwater` into `.DesiccantSensor`
- [x] @mripp Combine equivalent questions in Survey into "Transducer Status"

**Comment by mmannion** [comment]
- Updated `LocationVisit` desiccant columns:
  - Removed `DesiccantStage`
  - Removed `DesiccantGroundwater`
  - Added `DesiccantSensor`
