### ISSUE TITLE
Assess feasibility of using Field Maps / Windows 11

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#108]
Field Maps requires Windows 11. Need to ask Yamila if field devices are able to run Windows 11 and, if to, timeline for upgrade.

If unable to upgrade to Windows 11, will use ArcGIS Explorer instead.

# To Do

- [x] @kprice-TLH Update field computer to Windows 11
- [x] @Bikechain Update field computer to Windows 11

**Comment by mripp** [comment]
Survey123 fieldapp is compatible with Windows 11 Pro and Windows 11 Enterprise minimum version 21H2 (64 bit)

https://doc.arcgis.com/en/survey123/faq/systemrequirements.htm

**Comment by mripp** [comment]
Will need to check to see if these are available for Windows: 11 Tera Term, HyperTerminal, Ott mini, Xterm, High Sierra

**Comment by SarahNWF** [comment]
IT- updating Katie and Steve's computers

**Comment by mmannion** [comment]
Field Maps runs in WSA on Windows 11, but not natively in Windows itself.
