### ISSUE TITLE
Collect / load photos for user testing

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#109]
Collect photos for user testing round 2 of:
- Location overview
- Measuring Point(s)

Focus on Location that will be tested.

Note that we will store incoming photo data on a file server, not the repo (because of its size).

# To Do

- [x] @SarahNWF create location for storing photo data (e.g. `ent-gis`) with appropriate access
- [x] @Bikechain collect photos
- [x] @kprice-TLH Add MP photo comments in Aquarius
- [x] @craignwf Export Location / Measuring Point photos from Aquarius
- [x] @craignwf Add photo comments field to photo export
- [x] @craignwf Rename index file in repo to omit datestamp
- [x] @mmannion Write geodatabase data loader from exported Aquarius photos
  - Make photo loader stand-alone so we can run it without doing a whole new geodatabase deployment

**Comment by SarahNWF** [comment]
Created a folder in Ent-GIS for Katie and Steve
\\ent-gis\Imagery\Hydro_Survey_Photos
Sending them the file path once IT provides the access.

**Comment by mmannion** [comment]
- [ ] @craignwf Export Location / Measuring Point photos from Aquarius
- [ ] @mmannion Write geodatabase data loader from exported Aquarius photos

**Comment by craignwf** [comment]
> 



> * [ ]  @craignwf Export Location / Measuring Point photos from Aquarius
> * [ ]  @mmannion Write geodatabase data loader from exported Aquarius photos
>   
>   * Make photo loader stand-alone so we can run it without doing a whole new geodatabase deployment

I've written something to export the metadata for attachment photos (type: LocationPhoto) and to download them.   We can discuss further on Monday

**Comment by mmannion** [comment]
From team meeting:
- MP photos are associated in Aquarius with the Location, not with a specific MP
- Photos have an "MP" tag that identifies them as an MP photos (as opposed to a Location photo)
- MPs have unique IDs in Aquarius
- Therefore, we are going to update the photo _Comments_ field in Aquarius to contain the MP unique ID
  - Format: `MP#<id>`
