### ISSUE TITLE
Create Testing Instructions for Round 2 Testing

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#113]
- [x] Create directions in wiki on how to download software
- [x] Create directions in wiki on how to use software while in field
- ~Create testing document/spreadsheet to ensure all sections of the survey have been tested~
- [x] Update testing instruction PowerPoint
  - See guide [here](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/tree/main/documents/user_guides)
  - Remove setup instructions (admin will do this now)
  - Update end user instructions (for both apps on WSA, etc.)

**Comment by mripp** [comment]
PowerPoint has been updated [here](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/blob/main/documents/user_guides/Hydrologic-Monitoring-Project-Fieldwork-Instructions.pptx)
@kprice-TLH @SarahNWF

**Comment by SarahNWF** [comment]
Added the offline basemap side loading instructions to the wiki. 
The updated power point looks good to me, it's easy to follow.
