### ISSUE TITLE
Configure Field Maps Pop-ups and Feature Service

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#114]
- [x] MLR will publish a new service
- [x] MLR will configure the pop-ups in the FieldMaps to include the relevant fields for that layer
- [ ] ~MLR may look into adding a summary in the pop-up that indicates if the battery was replaced during the previous site visit~

**Comment by mripp** [comment]
Question for 7/24 Meeting:

Where on the server should the service be published? Should it be located under the "Hydro" folder?
Is "Hydrologic Monitoring" a proper name for the service?

**Comment by mripp** [comment]
Questions for 7/21 Meeting: 
Do they need to access the Data Logger and Sensor in Field Maps for any reason?
Review what fields are necessary to see in each section

**Comment by mripp** [comment]
MLR sent Katie and Steve screenshots to review for the 14th meeting

**Comment by kprice-TLH** [comment]
[Pop-Ups in Field Maps_20230814.docx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/12352892/Pop-Ups.in.Field.Maps_20230814.docx)
 Reviewed document with Steve. Comments in red @mripp

**Comment by mripp** [comment]
Update:
- Removed images of Location and Measuring Point
- Reworded all section to match survey form
- Added border around table
- - Removed 1 sensor from Stage section (duplicate)

Discussion:
- Battery not DOA question
- Adding Stage to Discharge section
- Add Rainfall TB cleaned

**Comment by mripp** [comment]
Updates Include:
-  Adding Photos back to Location and Measuring Point sections
- Only showing time (not date and time) when looking at the related records in the Rainfall False Tips, Stage, and Groundwater sections
- Add the Measuring Point name when you see multiple Stage or Groundwater measurements

Still Need to:
- Add Stage and Discharge in the same section
- Add Rainfall and Rainfall Tips in the same section

- [ ] Option to submit a ENH to hide the related records if no data is present

**Comment by mripp** [comment]
In the Location Visit table I added a note to "See Below for Details" if there is a Stage, GW, Temp, Conductivity, Rainfall False Tips collected and viewable in the related record section. This is the easiest way to configure the results and prompt the user to go down below

**Comment by mripp** [comment]
MLR will double check spelling, date format, and review all sections before next meeting
