### ISSUE TITLE
Discussion of Decimal Place Restrictions (Esri Cases #03429813, #03424796)

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#117]
The survey is set up to ask for 1 or 2 decimal places for certain inputs. The constraint is throwing an error if you try to enter x.0 or x.00.

![Image](https://user-images.githubusercontent.com/55856222/255731919-05eea210-1c36-4b79-8c4e-d0f4e680170d.png)

To fix this we can...
1)Update the hint to say "Enter to the nearest 1 decimal place. Exclude trailing zeros."
2)Remove the constraint and just have the hint. This would hypnotically allow users to enter 12.543

**Comment by mripp** [comment]
Implement Fix #1. 

@mripp will work with @rkircher to submit a bug

**Comment by mmannion** [comment]
- @rkircher create enhancement request to allow ".0" as a valid one decimal place value

**Comment by mripp** [comment]
MLR met with tech support on 9/1 and discussed options to modify the regex formula or to add an ENH to have an input mask for decimals. 

The workarounds provided (input mask on text, and spinner format) were not a viable workaround

**Comment by mripp** [comment]
Tech Support created an **ENH-000152001**: Survey 123 Connect should have an input mask that allows the user to limit the number of digits in a surveys response before or after the decimal but not constrain both sides of the decimal. to this case for the formatting issues we noticed when testing the body::esri:inputMask parameter as a workaround.

As the primary issue is with the regex expression, I was informed that the best next steps for the user would be to make a post in Esri Community in [ArcGIS Ideas](https://community.esri.com/t5/custom/page/page-id/arcgis-ideas) describing this issue as opposed to us requesting a new Enhancement.

**Comment by mmannion** [comment]
Recommend escaping the dot character in the regex above. Note the addition of a backslash before the dot:

`^[0-9]+\.\d{2}$`

The dot is a wildcard, and will match anything. For example, the original regex will match both:

123.45
123x45

In this case, we want to match a literal dot, so we need to escape it.

**Comment by mripp** [comment]
MLR updated the following questions in the Survey to reflect the new regex statement and also utilizing a text field

`BatteryVoltage` in the DataLogger section. 
`FalseTipCount` in Rainfall section 
`ManualLevel` "Manual Temperature in Celsius" in Temperature 
`SensorLevelInput` "Sensor Temperature" in Temperature section
`BatteryVoltage2` "Battery Level" in Data Logger part 2 section (Line 270 can be hidden)
