### ISSUE TITLE
Add domain values to survey

### ISSUE THREAD

**Issue by SarahNWF** [NWFWMD-IT/Hydrologic-Monitoring-Project#119]
Once Michael deploys the database with the newest domains Morgan will update the domains in the Survey

https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/blob/main/documents/data_model/Survey123_Domains.xlsx

**Comment by mripp** [comment]
When publishing Survey123 I am prompted if the domain values do not match the database domains. The survey can still be published if the domains do not match but this is a good cross-check. 

When fixing the domains I noticed a needed fix with the Hydro_Staff domain #124 

@mmannion I also have a question about the `Groundwater Adjustment Exception` domain and `Reading Type` domain. Currently these domains have a dash (-) in the label. Is there also a dash in the coded value?

**Comment by mmannion** [comment]
> Is there also a dash in the coded value?

Yes. The NWFWMD geodatabase standard is to use the same values the code and the description.

This approach is more verbose, but less ambiguous. For example, all ArcGIS Pro users will see the same values in their tables, independently of the _Show domain and subtype descriptions_ setting. Similarly, dashboard/code/etc. developers work directly with the values that the end users see, without having to translate between coded and human-readable values; although this makes for additional typing, it reduces coding errors.

**Comment by mripp** [comment]
Confirmed all domains in the survey have a dash for both the label and code
