### ISSUE TITLE
Hide Inventory Sections when Applicable

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#123]
There are instances when the Location doesn't have certain Inventory types
- Location may not have a Measuring Point
- Location may not have a Sensor
- Location may not have a Data Logger and Sensor

The survey should dynamically hide these repeat sections if these items aren't available in the database (related to #120  & #121)

**Comment by mripp** [comment]
@mmannion lets discuss the option of having a field in the location table for HasMeasuringPoint, HasDataLogger, HasSensor. This would follow the same format as the other sections and would easily allow me to hide the inventory section in the Survey

**Comment by mmannion** [comment]
Per team meeting:
- @mmannion Add `HasMeasuringPoint` and `HasSensor` columns
- Update data loader to populate these from `District Monitoring.xlsx`
  - @kprice-TLH Document logic
  - @mmannion Update loader
- @mripp Update

**Comment by mripp** [comment]
Mripp added the 2 new fields into the survey `Location.HasMeasuringPoint` and `.HasSensor`
Inventory section will dynamically show or hide these sections depending on what is available at that location

Example to demo: 

- All 3: 000004
- No Sensor: 000029
- Only MP: 000072
- No MP: 008546

Question: Are there instances when there are none of the 3 available? Looks like location 008094 is one. In this case should we hide the inventory section all together?

**Comment by mripp** [comment]
@mmannion it looks like the loader has been updated but can you confirm?

**Comment by mripp** [comment]
Survey has been updated to hide inventory section if no logger/sensor/MP
