### ISSUE TITLE
Compatibility between FieldMaps on Windows Subsystem and Survey123 on Windows (BUG-000160289)

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#127]
A BUG was submitted by Robert on 7/13/2023.

When using ArcGIS Field Maps on Windows 11 within the Windows Subsystem for Android (WSA), the link to open a survey in the app does not work despite the app being already installed.

To get around this we have installed both Field Maps and Survey123 on the Windows Subsystem for Android (WSA). Related to #112

**Comment by mripp** [comment]
Tech Support provided a workaround of "Use this workflow in ArcGIS Online, where it works as intended."

**Comment by mmannion** [comment]
@mripp to test ArcGIS Online workaround

**Comment by mripp** [comment]
I confirmed that the same behavior also happens in ArcGIS Online. I made a video which @rkircher will send along to tech support.

**Comment by mmannion** [comment]
This is now out-of-scope because we are not going to use WSA.
