### ISSUE TITLE
Update Location Issue Type domain values

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#140]
Per user testing round 2 feedback (2024-01-26 meeting):

- Rename
  - 'Inventory updated' to 'Changes to equipment'

- Add
  - 'Unable to connect'
  - 'No equipment installed'

The rename supports related changes to the survey UI - we're switching from using "inventory" to "equipment", and the specific wording of the domain value matches that of a related survey question.

# To Do

- [x] @mmannion Update data model deployment script to include new domain values
- [x] @mmannion Update data model diagram
- [x] @mripp Update survey to use new domain values from geodatabase

**Comment by mmannion** [comment]
Review this ticket and #128 to standardize _Location Issue Type_ domain value names, per existing pattern. If possible, use a prefix, like most existing values do, to aid visually searching through the pick list.

For example, we may want to rename the changes proposed above to something like:

- Changes to equipment > Equipment - Changed
- No equipment installed > Equipment - Not installed
- Unable to connect >Data logger - Cannot connect

These are just suggestions to illustrate the point; need to confer with @kprice-TLH .

**Comment by mripp** [comment]
@mripp updated the list in the survey for an example of the changes above

**Comment by mmannion** [comment]
Updated _Location Issue Type_ domain values are, in order:

> Equipment - Data logger failure
> Equipment - Device changed
> Equipment - None installed
> Equipment - Solar panel
> Equipment - Transducer failure
> Equipment - Unable to connect
> Follow up - Conduit adjustment/repair
> Invalid data - Battery change
> Invalid data - In-Situ low battery
> Invalid data - Station maintenance
> MP - Inaccessible due to high water
> MP - Missing (washed away, etc.)
> MP - New
> MP - No water at MP
> Vandalism - Data logger
> Vandalism - Enclosure
> Vandalism - Solar panel
> Vandalism - Transducer
> Other

@kprice-TLH, the screenshot in the preceding comment includes the word "issue" for domain value "Equipment - Solar panel issue". The annotations from our meeting on this domain show that word as stricken. Please confirm whether to keep or remove "issue".

**Comment by mmannion** [comment]
Added "issue" back to "Equipment - Solar panel issue"

**Comment by mripp** [comment]
Confirmed DB change matches with Survey123 domains - can be closed
