### ISSUE TITLE
Hide all WebMap that Shouldn't Appear in FieldMaps app

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#142]
During testing the team was confused why the Hydrologic Monitoring Field Collection (Survey123) map was showing up in the FIeld Maps application. When a new web map is created it automatically shows up in the FieldMaps app. It will be the admin or creators responsibility to hide this map. Directions: https://doc.arcgis.com/en/field-maps/11.1/prepare-maps/configure-the-map.htm#ESRI_SECTION1_C30D73392D964D51A8B606128A8A6E8F
- [x] Morgan to hide Hydrologic Monitoring Field Collection (Survey123) in FieldMaps
- [x] Sarah to hide all other maps that are shared at the organization level

**Comment by SarahNWF** [comment]
I went ahead and hid Hydrologic Monitoring Field Collection (Survey123) in FieldMaps as well.
