### ISSUE TITLE
Add Workspace XML to repo

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#15]
Depends on:
- #9 
- #10 
- #11 
- #12 
- #14

**Comment by mmannion** [comment]
@mripp FYI, a Workspace XML copy of the data model is in the `geodatabase` folder. I'll keep this updated to match the deployment scripts / diagrams from now on. Thanks for your patience while I caught everything up to this point.

**Comment by mripp** [comment]
Thank you @mmannion! I was able to download the new XML database and will use this with my survey. Just let me know if it gets updated again.

**Comment by mmannion** [comment]
@mripp I just pushed an updated about the same time your comment above arrived. The newest copy has (at least) two changes that are easy to spot:

- `WaterQualitySensorPulledDate` is now `WaterQualitySensorPullDate` (no "ed")
- `WaterQualitySensorReinstalled` is now `WaterQualitySensorReinstallDate`

I committed updated diagrams at the same time, so if you find that you have an earlier copy of the Workspace XML, it's probably best to fetch fresh copies of the PDF diagrams, too.

**Comment by mripp** [comment]
@mmannion sounds great! I made changes to the survey on Friday but most likely won't get to it until after our meeting on Wednesday. So I will make sure and grab the latest version whenever I work on this.
