### ISSUE TITLE
Adjust Logger Time Calculation

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#151]
Under new section "Logger Time", change Time Adjustment (minutes) allowable to 2 minutes instead of 1 min 
1 minute should be acceptable, 2 minute should show prompt to adjust
- [x] Make note red

![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/0e0e6850-ec85-4fa6-817c-11163dabb6d3)

**Comment by mripp** [comment]
Fixed this calculation in both the 1st and 2nd Data Logger Time sections
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/14140d28-a011-40bf-9d55-5c1927ae259e)

It was noted in the Round 2 Testing Document that: _During Conductivity Testing by Jacob revealed time check for Logger vs laptop not helpful, most people may  just auto populate with the current time for both.

Alternative:  box for number of minutes adjusted, leave blank if none adjusted?_

**Comment by mripp** [comment]
Reopened -- Is there ever an instance when the Laptop time is less than the data logger time? 

If so - I will need to update the time adjustment calculation to be an absolute value
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/39065935-a01f-46cd-886f-0573a8576fb1)

**Comment by mmannion** [comment]
Make "Time Adjustment (minutes)" values abs()
