### ISSUE TITLE
Determine How to Enter Negative Sign on Tablet

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#157]
When Katie used the tablet she couldn't select the negative sign for Water Level from MP in the Groundwater Section
Sarah to test on the tablet and figure out how to get the button to work.

![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/2d51e422-a299-4c8c-934d-79571d602cb4)

**Comment by SarahNWF** [comment]
Found the solution, users need to quickly double tap the button.
