### ISSUE TITLE
Update Temperature Serial Number domain values

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#167]
See annotations in data model diagram from 2024-02-09 meeting.

- [x] @mmannion Update data model
- [x] @mripp Update domain values in survey

(Note: Ticket was duplicated in #160)

**Comment by mripp** [comment]
Discussed on 2/26 meeting - change in database will be made at a later time

**Comment by mmannion** [comment]
- Updated _Temperature Serial Number_ domain per annotations in data model diagram
- Added `TemperatureMeasurement.SerialNumberComments` column to support 'Other' domain value
