### ISSUE TITLE
Change Battery Condition to Battery Needs Replacement

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#168]
Change wording of _Battery Condition_ and associated domain (good/poor) to something like "Battery needs replacement?" with yes/no.

Verify question / domain / etc. wording with @Bikechain and @kprice-TLH 

Options:
Remove data field `LocationVisit.BatteryCondition`
Remove data field `LocationVisit.BatteryCondition2`
Add data field `LocationVisit.BatteryNeedsReplacement` with domains yes/no

Workflow:
Battery is not DOA -->'Yes' Battery needs to be replaced --> Battery is replaced in the Logger File section
Battery is DOA --> 'Yes' Battery is replaced --> Only the battery volage is recorded

- [x] @mmannion to update database
- [x] @mmannion to update workflow diagram
- [x] @mripp to update survey logic
- [x]  @mripp to connect to new database field after database update

**Comment by mripp** [comment]
@mripp updated the 1st and 2nd battery section and can demo during the next meeting

**Comment by mmannion** [comment]
- Removed domain _Battery Condition_
- For table `LocationVisit`:
  - Removed column `BatteryCondition`
  - Removed column `BatteryCondition2`
  - Added column `BatteryNeedsReplacement`
- Updated data model diagram
- Updated workflow diagram

**Comment by mripp** [comment]
Tested with record 00004 on 3/18/2024 at 10:07 & 10:08
