### ISSUE TITLE
Deploy latest data model to sql-gis

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#170]
- [x] @craignwf Export MPs from Aquarius to repo
- [x] @kprice-TLH Upload latest District monitoring spreadsheet to repo
- [x] @mmannion Deploy latest data model / data to sql-gis

**Comment by craignwf** [comment]
Latest MPs (Reference_Points.csv) uploaded.   DisplayOrder from previous file joined to new file

**Comment by mmannion** [comment]
Updated model and data are deployed to sql-gis.

Yamila fixed Citrix for today, and sent files/instructions to transition to VPN for better remote access stability.

**Comment by mripp** [comment]
@mmannion I added a checkbox in this ticket. Every time the DB gets redeployed the measuringpoint.csv also has to get updated. Note for next time

**Comment by craignwf** [comment]
*LocationPhotos and ReferencePoints updated on github
*updated Location Photos downloaded to ent-gis location
