### ISSUE TITLE
Populate test data for location 222222

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#179]
Test location 222222 failing to load because flagged as rainfall location but does not have tipping bucket. Need to update district monitoring spreadsheet.
- [x] Update district monitoring spreadsheet to populate all dependent values for test location 222222

(Wrote quickly during meeting; call @mmannion for details)

**Comment by kprice-TLH** [comment]
Added sensor TB3 and accompanying Serial Number for location 222222
