### ISSUE TITLE
Research notification solutions for survey submissions

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#186]
# Business Needs

- Notify Katie when new survey is submitted with:
  - Discharge
    - Discharge submissions require review before uploading to Aquarius (read-only in Aquarius)
  - Location Issue

- Ideally, would like real-time and report solutions
  - Real-time supports circumstances when discharge is time sensitive

- Specifically do _not_ want notifications on all survey submissions
  - Too much noise
  - Need to focus on discharge / location issue

# Possible Solutions

- Dashboard
  - Katie can proactively look for new discharge / location issue submissions

- Survey123 notification / automation
  - Send email when new survey with discharge / location issue is submitted
  - Where to configure this?
    - Survey123 PowerAutomate plugin
      - District currently uses this
    - Feature service webhook
    - Make (name of website with automation service; formerly Integramat)

**Comment by SarahNWF** [comment]
Working on a power automate workflow. The ArcGIS Enterprise app in power automate only works with Enterprise 11.0 and above. Looking into creating custom connector (this was the old workflow before ArcGIS Enterprise was added to power automate).

**Comment by mmannion** [comment]
Per @kprice-TLH need to itemize conditions that trigger a notification.

Adding @kprice-TLH to ticket for defining business requirements.

**Comment by mmannion** [comment]
Options:
- Script (e.g. Python): Monitor feature service on schedule
- Webhook - Need to investigate granularity
- DBMS Trigger
