### ISSUE TITLE
Research GDB attachments format for Survey123

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#21]
While researching another topic I read some information that may impact how we store geodatabase attachments for the hydro survey, and that may impact the version of ArcGIS Enterprise we run. In [this ](https://enterprise.arcgis.com/en/server/latest/publish-services/windows/prepare-data-for-feature-services.htm#ESRI_SECTION1_3B4FB50BF9C64B91845FA93006601D5F) doc, at the bottom of the _Enterprise or workgroup geodatabase-specific requirements_ section, there is a discussion of the _Upgrade Attachments_ geoprocessing tool and a caution about the impact on ArcGIS 10.8.1, including the following statements:

> Upgrading attachments allows Survey123 to associate the images that people submit through the survey with specific survey questions. If you don't upgrade your existing attachments, images are still stored with the survey but will not be associated with a specific survey question. 

This may offer a solution to a potential issue we discussed in the 2022-09-26 team meeting in which one table may have multiple, logically different types of attachments. For example, the logical model for the `LocationVisit` table has four, separate attachment "properties":

- DataLoggerTimeSeries
- ADVMTimeSeries
- DischargeDataFiles
- DischargeTransectPhotos

Even though these are listed as separate properties in the diagram, in reality all attachments are stored in a single related table in the geodatabase. There are no actual attachment columns on the source table and, with the exception of the attachment names, there is no indication of their intended purpose; they're just a collection of files related to a visit.

This new upgraded attachments format sounds like it will let us treat the attachments in the survey the way that they are shown in the logical model diagram - with different attachment types for different purposes. It's worth investigating this further.

@mmannion (geodatabase) and @mripp (survey) should discuss this to determine if the upgraded attachment format has value for the hydro survey. If this results in a recommendation to upgrade the attachments format, it looks like an ArcGIS Enterprise version upgrade would also be required, at which point @SarahNWF should advise from a business / infrastructure perspective.

**Comment by mripp** [comment]
Hi @mmannion this information is good to know. It seems after running this tool we will be able to have seperate attachment 'Questions/prompts' for each attachment which will be nice for the field worker. 

Before we explore this functionality though we need to have a discussion on the file format and size for the 3 attachments:
- DataLoggerTimeSeries
- ADVMTimeSeries
- DischargeDataFiles

This [web page](https://doc.arcgis.com/en/survey123/desktop/create-surveys/xlsformmedia.htm#ESRI_SECTION1_A2F2DA5ADD8646B99D2344DF4595CD4B) explains the file types supported by Survey123 Connect. I am curious they are looking to upload

**Comment by mmannion** [comment]
Add Steve as assignee when GitHub account is ready

**Comment by mripp** [comment]
Confirmed the file types CSV, ZIP, Text, XML, and PDF can be uploaded via Survey published to Hosted Feature Service
The file "000749_20220912Q_0" for Discharge exceeded maximum file size and couldn't be uploaded. Will need to confirm this error also occurs with Enterprise. 


![Image](https://user-images.githubusercontent.com/55856222/198909187-d4904c50-347b-4bb6-a67c-e4127a69359a.png)

**Comment by mripp** [comment]
@mmannion After testing the attachments I do not think we need to run the _Upgrade Attachments_ geoprocessing tool on the database since it is working properly without running the tool. I have set up the Survey to allow separate questions/prompts to upload the files in each of the Data Logger, ADVM, and Discharge sections. After uploading the example [data files](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/tree/main/data) I confirmed all the files were uploaded to the single attachment related table in the geodatabase.

In addition, I have set the bind::esri:parameters setting to max-size=100 which allows each individual file to be uploaded at 100MB or less. This can be adjusted at anytime.

**Comment by mmannion** [comment]
Closing this research ticket. Following up with #59 to upgrade geodatabase attachments format. Confirmed during today's team meeting that new format requires minimum release of 10.8.1, and that we're running 10.8.1. So, no Enterprise upgrade required.
