### ISSUE TITLE
Add / review domain values

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#24]
The current draft of the data model includes several domains in various states of development: empty, partially complete, finished.

Review all domains to:
- Add values to those that are currently empty
- Review, and update if necessary, those with some initial values

**Comment by mmannion** [comment]
Unique lists from District Monitoring spreadsheeet.

Adding to domains for testing, but need review.


### Data Logger Type

CDMALink
High Sierra 3208
In-Situ Level Troll
In-Situ Level Troll 500
In-Situ Level Troll 700
Keller CTD (68m), Keller CTD (77m)
OTT Orpheus Mini
OTT Orpheus Mini-11 M, 0-4
Rugged Troll 100
See 12697 - North Bay Tide
Storm3
Sutron 7310
Sutron 9210
Sutron 9210 Xlite
Sutron Satlink 3
WaterLog H500XL
WaterLog H500XL
WaterLog H522+
XLink 100
XLink 500


### Sensor Type

15 foot cord
30'cable
Aqua Troll 500
Cable
Channel Master
Channel Master/OTT Mini
Druck
Druck PTX1835
In Situ Level TROLL
In Situ Level TROLL 500
KPSI 500
Keller
Keller AccuLevel
Keller Acculevel
Keller Acculevel 30'
Keller PT
Level Troll 500
OTT PLS
OTT PLS-15 M
OTT PLS-C
Sontek Argonaut
Sontek SL 1500
Sutron RLR
WaterLog Pulse Radar
Waterlog Encoder H-3311

**Comment by kprice-TLH** [comment]
[Survey123_Domains.xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/12131636/Survey123_Domains.xlsx)
Domain values added in attached excel file.

**Comment by kprice-TLH** [comment]
[Survey123_Domains_20230724 .xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/12152355/Survey123_Domains_20230724.xlsx)

Updated version of domains addressing #93

**Comment by mmannion** [comment]
Updated spreadsheet with comments:
- Kept original _Sheet 1_ worksheet as-is
- Added one new worksheet for each domain to include feedback
  - Items requiring review are highlighted in yellow


[Survey123_Domains_20230724-MCM.xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/12188978/Survey123_Domains_20230724-MCM.xlsx)
