### ISSUE TITLE
Install Excel on servers

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#26]
Excel is required for editing the survey with Survey123 Connect
@mmannion follow up with James, and include machines:
- [x] sql-gis
- [ ] ent-gis

**Comment by mmannion** [comment]
- Verified `sql-gis`
- Emailed James/Josh asking to add to `ent-gis` as well

**Comment by mmannion** [comment]
Asked Josh for status update. Said it can wait if busy, and asked for anticipated timeline, for planning.

**Comment by mmannion** [comment]
Josh just installed. Logged in and confirmed.

@mripp Excel is ready on `ent-gis`. Please install whatever you need (e.g. Survey123 Connect), but just coordinate with Sarah if it requires a reboot.

**Comment by mripp** [comment]
Survey123 Connect with Excel is set up on 'ent-gis'
