### ISSUE TITLE
Discussion on Bringing the Field Apps Offline

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#29]
Discussion on how Explorer and Survey123 need to be set-up in order to be offline capable

Also adding this information to the wiki

**Comment by mmannion** [comment]
See if there is the option to use the Collector / ArcMap type sync workflow that does not require the interim scheduled packaging step.

**Comment by mripp** [comment]
I confirmed that we don't need to repackage the offline map area on a scheduled interval. 

The user will be able to update the map area 'On Demand' and it will sync to the database at that time. 

I updated the Offline wiki accordingly
