### ISSUE TITLE
Publish Feature Layer for Use in Survey123

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#34]
The feature service that will be used in the Survey123 form to collect new values during the site visit will need to be published. This service will be published as a table. Please note when publishing the layers will need to have all spaces removed. The service will include the following tables

- LocationVisit
- LocationIssue
- VisitStaff
- RainfallFalseTips
- StageMeasurement
- GroundwaterMeasurement
- ConsucitivtyMeasurement
- TemperatureMeasurement

![Image](https://user-images.githubusercontent.com/55856222/194908078-d5de9959-29af-47ad-87ef-153a4ab2db40.png)

**Comment by mripp** [comment]
@mmannion Let me know if you would like to talk over this issue. I see we have 2 options if we want them to start testing sooner rather than later

1) I can create this as a Hosted Feature Layer as a temporary workaround
2) You can publish this layer from the SDE with the script you have developed

There might be other options I am not thinking of too!

**Comment by mmannion** [comment]
Thanks - I have a list of questions for you about this, offline requirements, and the CSV file from the wiki. They're separate issues, but with some common subtopics. I've been reading/testing today so I don't waste your time with things I can learn on my own; I'll be back in touch when I know enough to ask a sensible question.

FYI, I opened a support case today about #25, as well. I can publish a service manually, but get the dreaded 999999 error when using Python. Did a screenshare with a support analyst and confirmed the issue; he's checking with a colleague.

So, for now, please do whatever is easiest to keep working on the survey (e.g. hosted, or manually published from geodatabase).

**Comment by mripp** [comment]
@mmannion Okay sounds good thank you! For now I will probably publish a hosted feature layer and connect the survey to that so things move along for testing. Thanks for the heads up on the script.

**Comment by mripp** [comment]
Published Hydrologic Fieldwork Location Visit hosted feature layer to Portal (id: 40a21edb01f3495bb107920549ccde79)

**Comment by mripp** [comment]
Confirmed that fields can be uppercase in Survey123 Connect when connected to an EGDB
