### ISSUE TITLE
Create Offline Enabled Basemap for ArcGIS Explorer and Survey123

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#36]
The ArcGIS Explorer Field or Field Maps application will need to use a basemap that is enabled for offline. We can publish the imagery as a Vector Tile Layer and/or Vector Tile Package
https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/create-an-offline-map.htm

More info:
https://resources.esri.ca/getting-technical/taking-arcgis-field-maps-offline-with-arcgis-enterprise

- [x] Sarah to create tile packages for Imagery
- [x] Sarah to add Offline Streets basemap to Portal (used in FieldMaps)
- [x] Morgan to add Offline Streets basemap to FieldMaps
- [x] Morgan to add imagery basemap to FieldMaps
- ~Morgan create predefined area for FieldMaps~
- [x] @SarahNWF create sideloaded basemap
- [x] Morgan to link vector tile package to Survey123 (Streets Only)

**Comment by mripp** [comment]
On 12/12 we discussed having a Street and Aerial basemap available for the whole district. We will need to create a packaged tile layer for each. 

Sarah will give us the ArcGIS Online credentials and also the outline of the boundary

**Comment by mmannion** [comment]
Research adding District aerial imagery as basemap (per team meeting)

**Comment by mripp** [comment]
Recommended to create a Vector Tile Layer and/or Vector Tile Package for use in offline maps 

https://pro.arcgis.com/en/pro-app/latest/help/sharing/overview/create-an-offline-map.htm

**Comment by mmannion** [comment]
@SarahNWF to review communications with Philip Royal > decide how to proceed.

**Comment by SarahNWF** [comment]
Created a test map for Offline use in explorer. Users can download areas they'll be working in if they want District aerial imagery out in the filed. So far I only have a small portion of Holmes County. Going to try with whole counties (if space allows in Ent-GIS) some of these tile packages can get large.

**Comment by mmannion** [comment]
- Need input from @Bikechain on highest resolution imagery required for area immediately around Location
- Determine if / how to side-load entire district imagery on each field device
  - Consider clipping imagery to buffer around each Location, if contiguous imagery is too large
- Create tile package for offline use for "normal" street navigation basemap
  - Note that street basemap will likely be for general reference, not navigation; users more likely to navigate using their phone than laptop
  - Reassess this when moving to tablets in the future

**Comment by SarahNWF** [comment]
[Portal item URL for offline compatible basemap](https://geoservices.nwfwmd.state.fl.us/portal/home/item.html?id=1db0656a79d4490fa7dfaae1e39caba8)

**Comment by mripp** [comment]
@SarahNWF when attempting to download the basemap offline in Field Maps I am getting a prompt to login to ArcGIS Online. Can you confirm the credentials were stored in the offline basemap? Should be able to check in the settings

**Comment by SarahNWF** [comment]
Each time I try to store the credentials with the basemap I get the "error generating token" message. I think when I uploaded the basemap during the meeting I forgot to store the credentials with the item. It might be why it worked that time when before it kept giving me errors. I'll try to look into why it keeps giving me an error.

**Comment by mripp** [comment]
@SarahNWF I tried to download an offline map area with your [Basemap Test](https://geoservices.nwfwmd.state.fl.us/portal/home/item.html?id=4e5df4bb6fab460b9599c740652cfc71) map but am still getting a prompt to login with ArcGIS Online credentials. So I don't think its working yet :(

As a test I tried to add this aerial basemap to the Portal, storing my own ArcGIS Online credentials but I get a different error. Curious if you get it too
https://www.arcgis.com/home/item.html?id=226d23f076da478bba4589e7eae95952

**Comment by mripp** [comment]
@SarahNWF Nice find! I was able to download an offline area in your Basemap Test map now. I also added this basemap to my working [webmap](https://geoservices.nwfwmd.state.fl.us/portal/home/item.html?id=080d67409613481086a8bc72858976ad) and was able to create an offline area on my phone. 

I will try and create a predefined map area in the Field Maps browser app next.  I am currently getting an error and will try and troubleshoot that next
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/2b669d5e-3804-4266-a52b-e7e72868eb67)

**Comment by mmannion** [comment]
Re: username case sensitivity, FWIW I found the same thing with Enterprise when... shoot, I can't remember. I think it behaved differently when logging in to Portal from a browser vs. connecting to the same Portal from Pro. It took me a while to realize what was happening.

Anyway, the takeaway is that we should be consistent in our upper/lower case patterns when creating user accounts from now on. I'm guessing that Okta will make this a non-issue for most users, so it's probably only admin accounts that we need to pay attention to.

**Comment by mripp** [comment]
I was able to create a pre-defined map area and download it to my phone/desktop. Will demo during the next meeting

**Comment by SarahNWF** [comment]
@mripp I added the Wakulla and Leon county buffered imagery areas to the Basemap Test webmap. I tried testing downloading offline areas on my phone, could you test it on your end when you get a chance?
The tile package itself is under the imagery folder in content - called "Leon_Wakulla".

I'll have more details for Monday's meeting.

**Comment by mripp** [comment]
@SarahNWF I was able to download an offline map area centered around Tallahassee (Level of Detail: World to Building). I was getting a message that "Map area is too large" when I tried to download the map area for the entire district

**Comment by mripp** [comment]
**To create an offline basemap for use in Survey123 there are 2 options**
1.  Use ArcGIS Pro to create a Vector Tile package and then upload this to Portal. This would require an update whenever the team wants to update the basemap ([documentation workflow](https://community.esri.com/t5/arcgis-survey123-blog/survey123-tricks-of-the-trade-configure-a-map-for/ba-p/1169513))
2. Use the Field Maps in ArcGIS Portal interface to create an offline map area. You can set an update frequency to update the offline map area BUT the field worker would still be required to refresh/redownload this onto their device each time. [(workflow documentation)](https://storymaps.arcgis.com/stories/723f914745a24e4d8baf0b9a66335666)

**Questions**
- Esri basemaps get updated every 3 weeks. How often would NW Florida need their basemaps updated?

**Comment by mripp** [comment]
On 11/13 we discussed that the Imagery basemap gets updated every 3 years so it would make sense to have the streets basemap for Survey123 updated on this same 3 year schedule.

**Comment by SarahNWF** [comment]
I submitted a ticket asking for assistance (or documentation I missed) with side loading the imagery tile packages onto the laptops.

**Comment by SarahNWF** [comment]
I was able to create a sideloaded basemap for offline use in Field Maps. It's a combination of the streets basemap and the imagery buffer areas. I created a single offline area of the District at the detail level we wanted. 

@mripp if you want to test it on Field Maps on your machine, you can download the tile package here: https://northw091-my.sharepoint.com/:u:/g/personal/sarah_hibbard_nwfwater_com/EcGh8PykQYVBvIO35DsKEfUBetQa2J0Bjc6XdUgelPWWUg?e=cVybSe
(GitHub won't let me upload this, it's too large)

Once you have it stored locally, follow these directions to transfer it to the Windows Subsystem for Android files: https://allthings.how/how-to-transfer-files-to-wsa-storage-on-windows-11/

Then you can set the tile package as the default offline basemap. I created the offline area in the app on the device.

![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/104779859/4e08975a-4099-4ba1-8ce6-0b8c38bace9d)
