### ISSUE TITLE
Add data loading to deployment

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#43]
- `Location`
- `MeasuringPoint`
- `DataLogger`
- `Sensor`

See `Data\District Monitoring.xlsx`

**Comment by mripp** [comment]
@mmannion for the next round of testing I think it would be useful to have a set of real locations, measuring points, data loggers in the data model. I can assist with this as well

**Comment by mmannion** [comment]
Initial data loader is complete. Results are consistent with all committed data model tickets.

Per 2023-03-13 team meeting, outstanding tasks include:
- Add Location / Measuring Point photos to loader (requires source data)
- Resolve known issues with source data that is currently failing validation checks (e.g. correct elevations for Measuring Points)
- Continue adapting data loader to match ongoing data model changes

Closing this ticket as complete. Will create new / updated existing tickets to address the list above.
