### ISSUE TITLE
Export Measuring Points from Aquarius

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#44]
- Measuring Point
  - Required
    - Elevation
    - Way to associate with Location
  - Desired
    - Name
    - AquariusID
    - Description
    - Comments
    - Photo

**Comment by craignwf** [comment]
Reference_Points_20221018.xls uploaded to Documents.  The file is flattened from the original nested json but its structure may require further discussion

**Comment by craignwf** [comment]
completed

**Comment by mmannion** [comment]
Moved spreadsheet from `documents` to `data`
