### ISSUE TITLE
Configure Survey with Linked CSV

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#54]
In order to reference the Measuring Point data in an offline environment the Survey will need to reference a linked CSV of the Measuring Point locations. The CSV file will be stored as an item in the ArcGIS Enterprise. Survey123 will check the CSV when a user enters the form's main page (the Collect/Sent/other folders page) and downloads any locations that have been updated. 

In the future, a script will need to be developed to automatically update the CSV based on the Measuring Point table in the database.

**Comment by mripp** [comment]
Uploaded csv to Portal and linked it into the Survey for the select_one MeasuringPoint option 
https://geoservices.nwfwmd.state.fl.us/portal/home/item.html?id=7afa5d29230944bfac72cd1b6a79bfdd

**Comment by mmannion** [comment]
Investigate creating relationship based on GlobalID
Name is not enforced as unique

**Comment by mripp** [comment]
Measuring Point CSV list updated to include 117 Measuring Points

**Comment by mripp** [comment]
This task will be incorporated into the new Git Hub Templates #173. So whenever a new MP location is added to the database OR if the database needs to be dropped or recreated then this step will need to be done by Sarah. 

I also included a copy of the detailed instructions in the [wiki](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/wiki/Deployment%E2%80%90Server#survey)
