### ISSUE TITLE
Verify tolerance in conductivity workflow

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#57]
The conductivity workflow includes two places where a pair of measurements need to be compared to see if they fall within a tolerance:

- Manual and real-time sensor levels
- Calibration verification standard and reading levels

Currently, both tolerances are set to 10%. One might need to be 5%, per documented procedures.

Verify if / which tolerance should be set to 5%. Upgrade survey / diagram accordingly.

**Comment by mmannion** [comment]
Update workflow diagram

**Comment by mmannion** [comment]
Reopening per new information from State SOP. See attached [email](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/10261884/email.pdf). Specific actions are:

- Change manual-to-logger comparison tolerance back to 10%
  - [ ] Update workflow diagram (@mmannion)
  - [ ] Update survey, if necessary (@mripp)

Keep the calibration tolerance at 5%.

**Comment by mripp** [comment]
@mmannion workflow diagram is correctly reflecting 5% for this workflow.
