### ISSUE TITLE
Create ArcGIS Enterprise users for survey testing

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#58]
- Required before 2022-12-01 testing kickoff meeting.
- Need minimum of _Field Worker_ user type
- Can share a user for testing, if not ready to deploy permanent Okta/Portal accounts

**Comment by SarahNWF** [comment]
"HydroField_Test" has been created in Enterprise
User Type: Creator
Role: User
