### ISSUE TITLE
Verify tolerance for temperature workflow

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#62]
Per the attached [email thread](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/10262300/email.pdf), we may need to update the tolerance for comparing manual and logger temperature measurements. Two possibilities exist:

- No change: Keep the existing 2°C tolerance for all workflows with a temperature component, or;
- Two tolerances: Keep the existing 2°C tolerance for ADVM only, and add a 0.5°C check for all other workflows

@Bikechain is researching the business requirement. Initially assigning this ticket to him.

If a change is necessary, document the requirements here and reassign the ticket to @mripp and @mmannion to update the survey and workflow diagram, respectively.

If it's necessary to update the workflow diagram, use the _After_ logic from the attached [draft](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/10262368/temperature.pdf).

**Comment by mmannion** [comment]
Confirmed tolerances in 2023-01-09 team meeting. Reassigning to:

- [ ] @mmannion - Update workflow diagram
- [ ] @mripp - Update survey

**Comment by mripp** [comment]
Modified survey to include 2 different temperature tolerances based on the sensor type
