### ISSUE TITLE
Sensor Adjusted Amount datatype in Conductivity Measurement table

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#64]
While configured the survey I noticed that the SensorAdjustmentAmount is an Integer. 
![Image](https://user-images.githubusercontent.com/55856222/216175913-d1f256d2-00b9-499a-b0a0-6c4ac34338a9.png)

I propose that this value is a **decimal** similar to the Stage and Groundwater tables. 

The reason for this is that I am unable to calculate the 5% threshold when the value is an integer.

**Comment by mmannion** [comment]
Per 2023-02-06 team meeting, hydrologists confirmed that conductivity measurements and adjustments will always be integer. Acknowledged that this differs from the decimal measurements/adjustments for stage and groundwater.


@mripp is it possible to perform the adjustment calculation in Survey123 if the `ConductivityMeasurement.SensorAdjustmentAmount` column remains an integer?

For example, will the survey let you perform the adjustment calculation using integer math? Or, can you round the decimal result to integer for storage?

I'm going to close this data model ticket for now. If the survey requires a change in the table to allow the calculation, let's talk; we can reopen this if necessary.
