### ISSUE TITLE
Add absolute value annotations to diagram

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#65]
Ensure in workflow diagram that any calculations requiring absolute value are annotated as such in general (blue) and target (green) callouts

- [ ] @mripp will check calculations for Stage, Groundwater, Conductivity in Survey123

**Comment by mmannion** [comment]
### Stage
- _Calculate sensor adjustment_
  - Corrected green annotation from `StageMeasurement.AdjustmentAmount` to `StageMeasurement.SensorAdjustmentAmount`
- _Difference <0.02'?_
  - Added green annotation to check absolute value of previously computed, signed `StageMeasurement.SensorAdjustmentAmount`

### Groundwater
- _Calculate sensor adjustment_
  - Corrected green annotation from `GroundwaterMeasurement.AdjustmentAmount` to `GroundwaterMeasurement.SensorAdjustmentAmount`
- _Difference <0.02'?_
  - Added green annotation to check absolute value of previously computed, signed `GroundwaterMeasurement.SensorAdjustmentAmount`

### Conductivity
- _Calculate sensor adjustment_
  - Renamed to _Calculate manual / sensor difference_
    - Better describes actual calibration process, per call with @kprice-TLH
    - Conductivity sensors aren't calibrated by a specific delta, like with stage and groundwater
    - Language matches what we already used for equivalent temperature calculation
  - _Difference <10%?_
    - Added green annotation with formula
    - Added blue annotation clarifying that 10% is relative to manual measurement (confirmed with @kprice-TLH)
  - _Difference <5%?_
    - No changes needed; preceding _Calculate verification standard / reading difference_ action already describes the process and states the formula

### Temperature
- _Difference <2°C?_ and _Difference <0.5°C?_
  - Added green annotations with formula:
    - Including `abs()`
    - Showing that difference is relative to manual measurement (confirmed with @kprice-TLH)

**Comment by mmannion** [comment]
@mripp I'll commit the updated diagrams to the repo in a few minutes; need to coordinate a batch of recent changes. Please review and post more comments/questions here if necessary, or close if appropriate. Thanks!

**Comment by mripp** [comment]
Confirmed Stage, Groundwater, Temperature calculations look good. 
Need to confirm the calculations for Conductivity on the next call
