### ISSUE TITLE
Delete TemperatureMeasurement.ManualLevelUnits

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#68]
Users will be able to enter either Celsius or Fahrenheit in the survey, but we will always store Celsius in the database. The survey will perform the necessary conversion. Therefore, the `TemperatureMeasurement.ManualLevelUnits` column is not needed.

**Comment by mripp** [comment]
@mripp set up Survey123 to record ManualLevel and SensorLevel in Celsius

**Comment by mmannion** [comment]
Updated `create_hydro_data_model.py` and data model diagram to remove:
- Domain: `Temperature Units`
- Column: `TemperatureMeasurement.ManualLevelUnits`

**Comment by mmannion** [comment]
Moving back to _Done_ and assigning to @mripp to update survey components

**Comment by mripp** [comment]
Survey asked for Logger Temperature and Units but don't write this to the database. Instead it converts it to Celsius and stores that in the database. 

Do they need to see the result in Celsius as a read only message? 
![image](https://user-images.githubusercontent.com/55856222/233732603-b3d258f9-67f8-4f1c-8b10-4e1d861a6944.png)

**Comment by mripp** [comment]
Change 'Logger Temperature Source' to 'Sensor Temperature Source'
Change 'Logger Units' to 'Sensor Units'
Create a message that shows the result in C

**Comment by mripp** [comment]
Question for next meeting:
- Should the Sensor Temperature be rounded to 1 decimal place when calculating the conversion of F to C?
