### ISSUE TITLE
Add active/inactive status indicator to MeasuringPoint

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#72]
Measuring Points can disappear or otherwise go out of use over time. Need to maintain old points in database for historical purposes (e.g. reporting) but field staff shouldn't be able to pick inactive ones during new site visits.

- [x] @mmannion: Add active/inactive indicator to `MeasuringPoint` table
- [x] @mripp: Filter measuring point list in survey to only show active points

**Comment by mmannion** [comment]
Added `MeasuringPoint.IsActive` column.

Initially set all Measuring Points that pass loading integrity checks to active ('Yes').

**Comment by mripp** [comment]
I have a filter set to only show active MPs. Since all the MPs in the database are active it would be good to get an inactive MP in the database to test this. 

- [ ] @mmannion to add MP locations that are inactive into database

**Comment by mmannion** [comment]
That's a good idea. We are going to overwrite this data periodically as we go, anyway, so just flip a few of the ones that are in there to inactive for testing.

Actually, feel free to edit whatever you like. If it gets totally hosed, it only takes 5 minutes to reload.

**Comment by mripp** [comment]
I updated the filter in the survey since it was creating an error with the survey when refreshing the inbox. 
![Image](https://user-images.githubusercontent.com/55856222/232494168-b970236a-d993-47b7-9bac-d4bbf0708f7f.png)
`query="IsActive='Yes'"`
