### ISSUE TITLE
Change how we store logger time adjustments

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#74]
If a Data Logger clock is wrong, we're currently storing how many minutes it needs to be adjusted. We also handle drift vs. clock reset adjustments differently.

Better solution is:
- User enters logger time/date, always
- Survey captures laptop time/date automatically when user enters that data
- Survey determines whether adjustment is necessary and prompts user to adjust, if so

### SEE ALSO #94

**Comment by mmannion** [comment]
Review attached time adjustment workflow draft at next team meeting

[time_adjustment_DRAFT.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/10975023/time_adjustment_DRAFT.pdf)

**Comment by mmannion** [comment]
Updated draft to incorporate @kprice-TLH feedback


[time_adjustment_DRAFT.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/11006541/time_adjustment_DRAFT.pdf)

[time_adjustment_TARGETS_DRAFT.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/11006542/time_adjustment_TARGETS_DRAFT.pdf)

**Comment by mmannion** [comment]
Confirmed new workflow with group. Make changes proposed in draft.

**Comment by mmannion** [comment]
**WORKING DRAFT**

These changes are uncommitted, pending feedback from @kprice-TLH. I don't want to lose track of them, though, so I'm leaving the list in this comment.


## Data Model Changes

### Add

- `LocationVisit` columns:
  - `DataLoggerTime`
  - `DataLoggerTimeActual`
  - `DataLoggerTimeAdjusted`
  - `DataLoggerTimeAdjustmentException`
  - `DataLoggerTimeAdjustmentComments`

- Domain `Time Adjustment Exception`

### Remove

- Column `DataLoggerTimeAdjustmentType`
- Domain `Time Adjustment Type`

**Comment by mripp** [comment]
Implemented in Survey can be reviewed during next meeting
