### ISSUE TITLE
Add comments fields for "Other" exceptions

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#75]
For domains with an "Other" choice, we currently have people recording comments as general `LocationIssue` records.

Change this to add a dedicated comments field in-context for each potential "Other" choice.

In the survey, only reveal the comments field if the user picks "Other". The goal is for all choices to be available in the domain over time; the other/comments pair is primarily intended to allow capturing new domain values to be added in the future (as well as the rare one-off values with no other category that will inevitably, but infrequently, arise).

Note that when loading to Aquarius, we want to:
- Load context-specific comments the relevant section, and;
- Concatenate all comments into a single block for the Location Visit

**Comment by mmannion** [comment]
Added comments columns:
- `ConductivityMeasurement.SensorAdjustmentComments`
- `GroundwaterMeasurement.SensorAdjustmentComments`
- `StageMeasurement.SensorAdjustmentComments`
- `LocationVisit` table:
  - `.BatteryReplacementComments`
  - `.DessicantMaintenanceComments`
  - `.RainfallBucketComments`
  - `.RainfallMechanismComments`
  - `.ADVMBatteryReplacementComments`
  - `.ADVMBeamCheckInitialComments`
  - `.ADVMBeamCheckSecondaryComments`
  - `.ADVMCleanedComments`

Updated supporting documentation:
- Data model diagram
- Workflow diagrams
- Geodatabase XML Workspace


### Questions for Next Team Meeting

(@kprice-TLH please review before next meeting if you have time)

1. Can one `LocationVisit.DessicantMaintenanceComments` comments column cover all three dessicant types?

2. Does `LocationVisit.ADVMMaintenance` need comments?
- No domain values yet, so not sure if there will be an "Other"
- Probably worth compiling domain values (#24) at this point, even if only a first draft

3. Do `.ReadingType` columns need comments?
- Domain has "Other" value
- Column exists on tables:
  - `ConductivityMeasurement`
  - `GroundwaterMeasurement`
  - `TemperatureMeasurement`

**Comment by mmannion** [comment]
Answers for questions in previous comment:
1. [x] Yes - one desiccant comments column
2. [ ] Yes - add comments for `.ADVMMaintenance`
3. [x] No - existing "Other" choice in _Reading Type_ domain is incorrect. Remove it.

**Comment by mripp** [comment]
These new fields have been added to the Survey123. 

If the user selects "Other" from the dropdown a field will display to "Please describe"

Only question I have is that the Survey is not concatenating the fields together but rather the results will display as the following

`ConductivityMeasurement.SensorAdjustment` recorded as "Other"
`ConductivityMeasurement.SensorAdjustmentComments` recorded as "Unable to read sensor"

**Comment by mmannion** [comment]
That's correct.

Just to confirm, is the first column supposed to be `.SensorAdjustmentEXCEPTION` (just capitalized for emphasis here)?

There's a lot of similarly-named columns and I just want to be sure.

**Comment by mripp** [comment]
Yes that is correct! I updated it above.

This is completed in the data model and survey then and can discuss at our next meeting
