### ISSUE TITLE
Capture record method for stage

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#76]
Need to capture method staff used to measure stage and groundwater levels. Domain values are:

- Stage
  - Staff
  - Tape Up/Down
  - Wire weight
  - Other

Include comments for Other choices, per #75

**Comment by mripp** [comment]
@mmannion since we are starting to modify the Stage section on 5/1 it might make sense to implement the Stage domains next week. I would wait to do the GW domains since that might warrant more discussion

**Comment by mmannion** [comment]
- Added columns to `StageMeasurement`
  - `ManualMethod`
  - `ManualMethodComments`

- Added domain `StageMethod` with values:
  - `Staff`
  - `Tape up/down`
  - `Wire weight`
  - `Other`

**Comment by mripp** [comment]
mripp is capturing new fields in Survey
