### ISSUE TITLE
Add Aquarius ID to Reference Points spreadsheet

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#78]

**Comment by mmannion** [comment]
@craignwf The prior copy of this information was the Reference_Points.xlsx spreadsheet (in the [data](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/tree/main/data) directory of the repo). I see this new copy has basically the same information/structure, but is in CSV format.

Best practice is to overwrite the original file with the new one, to preserve existing references to it. GitHub will let us go back in time and see the original if we need to. Likewise, updated copies should not have datestamps in their name; GitHub tracks the change dates for us.

It may be the case here, however, that a change in format is appropriate. If the data comes out of Aquarius natively as CSV instead of Excel, for example, let's stick with CSV.

When you have a chance, would you please:

- Determine the best format for this file
- Then:
  - If Excel, overwrite the original file with one of the same name
  - If CSV, delete the original file and upload a new one in its place, using a file name without a datestamp

Thanks!

**Comment by craignwf** [comment]
Thanks Michael.  I deleted the previous spreadsheet and uploaded a csv in its place.
