### ISSUE TITLE
Add ADVM discharge start/end columns

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#79]
We need to add two new columns to the `LocationVisit` table:

- `ADVMDischargeRecordStart`
- `ADVMDischargeRecordEnd`

These are the appropriate targets for the bottom of the ADVM workflow, and did not exist previously.

During the ADVM workflow, there are up to three data file and associated start/end times that we need to record:

1.  Main ADVM data file, at the top of the workflow

and if performing a discharge:

2. Discharge data file, within the discharge workflow, from the discharge equipment
3. Additional ADVM data file, from when the device was in discharge mode (i.e. 1-minute interval logging)

**Comment by mmannion** [comment]
- Added columns to data model:
  - `LocationVisit.ADVMDischargeRecordStart`
  - `LocationVisit.ADVMDischargeRecordEnd`

- Updated data model diagram

- Updated annotations in workflow diagram

**Comment by mripp** [comment]
More discussion is needed on this because discharge is used in both the ADVM and Stage workflows.

**Comment by mripp** [comment]
On 5/1 we decided to place the ADVM Discharge Record Start/End fields and ADMV Discharge files in the Discharge section. These fields will only show if HasADMV=Yes and HasDischarge=Yes


![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/3eccb66a-8d21-40ff-9ba7-389b5d81ebba)
