### ISSUE TITLE
Correct spelling of "desiccant"

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#80]
I spelled "desiCCant" incorrectly as "deSSicant" all over the place. Fix the data model and diagrams.

@mripp, my apologies for the downstream work this will create.

**Comment by mmannion** [comment]
Corrected spelling in the following places

- Workflow diagram
- Data model diagram
- `LocationVisit` table column names and aliases:
  - `DesiccantEnclosure`
  - `DesiccantStage`
  - `DesiccantGroundwater`
  - `DesiccantComments`
- Domain `Desiccant Maintenance`

**Comment by mripp** [comment]
This has been fixed in survey
