### ISSUE TITLE
Discussion: Times should be in 24 hour time UTC (ENH-000132015)

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#85]
- [ ] Implement UK region on each device
- [ ] Remove 24 hour hints in Survey123 XLXS if workaround is confirmed working

During testing feedback it was discussed that the times should be in 24 hour time UTC. The following fields are impacted by this. 

- `LocationVisit.VisitDate`
- `LocationVisit.BatteryReplacementDate`
- `LocationVisit.DataLoggerRecordStart`
- `LocationVisit.DataLoggerRecordEnd`
- `LocationVisit.DataLoggerTime`
- `LocationVisit.DataLoggerTimeActual`
- `LocationVisit.ADVMBatteryReplacementDate`
- `LocationVisit.ADVMRecordStart`
- `LocationVisit.ADVMRecordEnd`
- `LocationVisit.ADVMDischargeRecordStart`
- `LocationVisit.ADVMDischargeRecordEnd`
- `LocationVisit.DischargeRecordStart`
- `LocationVisit.DischargeRecordEnd`
- `LocationVisit.WaterQualitySensorPullDate`
- `LocationVisit.WaterQualityPurgeStart`
- `LocationVisit.WaterQualitySamplingEnd`
- `LocationVisit.WaterQualitySensorReinstallDate`
- `RainfallTips.FalseTipDate`
- `StageMeasurement.MeasureDate`
- `StageMeasurement.SensorAdjustmentDate`
- `GroundwaterMeasurement.MeasureDate`
- `GroundwaterMeasurement.SensorAdjustmentDate`
- `ConductivityMeasurement.MeasureDate`
- `ConductivityMeasurement.SensorAdjustmentDate`
- `ConductivityMeasurement.VerificationDate`
- `TemperatureMeasurement.MeasureDate`

After researching the options for the Field Form I found the following:
- During publication of the feature service we can set the TimeZone to UTC. When doing this the DateTime field in the Survey will still appear with an AM/PM option and the data will still be stored with AM/PM
- In this [example](https://community.esri.com/t5/arcgis-survey123-blog/dates-and-time-in-survey123/ba-p/895528), Survey123 has the user input the time in military time but the field is datatype TEXT. 

@rkircher Ask Katie if we want to escalate this enhancement from low to high.

**Comment by mripp** [comment]
@kprice-TLH I am wondering if you have an example of how you need the date and time formatted in UTC time. Is it like so '12/17/2023 15:20:20'

**Comment by mripp** [comment]
On 4/17 we discussed how we can use other lanaugaes such as French, German etc to use 24 hour clock

- [ ] @mripp will look into using these languages that are 24 hours that  appear in English

Mripp also demoed how you can have a note/text field translate the 12 hour clock into a 24 hour clock for display purposes

**Comment by mripp** [comment]
The ENH is currently "[under consideration](https://support.esri.com/en/Bug-Enhancement-Status)" and we would need to escalate it in order for it to be implemented in a timely fashion. 

It was recommended by tech support to utilize the workaround mentioned [here](https://community.esri.com/t5/arcgis-survey123-blog/dates-and-time-in-survey123/ba-p/895528#toc-hId--1536682012). This would mean the user would input the date/time with the calendar interface and the survey would automatically convert it to military time and store it as a string. This would mean the database would need to contain 26 new string fields

**Comment by SarahNWF** [comment]
Followup with Michael to make sure the database preserves 24-hour time from UTC Timezone, preserve through databases, dashboards, etc. with Survey123

**Comment by mripp** [comment]
Update: The enhancement request is in the works on the datetime issue.  It's been pushed back to product team for escalation.

**Comment by mmannion** [comment]
> Followup with Michael to make sure the database preserves 24-hour time from UTC Timezone, preserve through databases, dashboards, etc. with Survey123

Confirmed.

The database stores dates and times in an internal format that is independent from how they are displayed in clients. Client applications can display this information in 12/24 hours, different time zones, etc. by choosing their own formatting options when fetching date/time content from the database.

**Comment by mripp** [comment]
Implemented a note to show 24 hour times for all questions in the survey. This is a temporary work around until this is fixed in the product. 
If this enhancement is implemented in the Survey123 product all fields below can be removed. In addition, the hint that references these fields can also be removed.

Fields used to calculate 24 hour note:
- `VisitDate24` in Location Visit section
- `BatteryReplacementDate124` in Battery section
- `DataLoggerTime24` in Logger Time section
- `DataLoggerTimeActual24`  in Logger Time section
- `DataLoggerTimeAdjDate24`  in Logger Time section
- `FalseTipDate24` in Rainfall section
- `StageMeasureDate24` in Stage section
- `StageSensorAdjustmentDate24` in Stage section
- `GroundwaterMeasureDate24` in Groundwater section
- `GroundwaterSensorAdjustmentDate24` in Groundwater section
- `WaterQualitySensorPullDate24` in Water Quality section
- `WaterQualityPurgeStart24` in Water Quality section
- `WaterQualitySamplingEnd24` in Water Quality section
- `WaterQualitySensorReinstallDate24` in Water Quality section
- `ConductivityMeasureDate24` in Specific Conductance section
- `ConductivitySensorAdjustmentDate24` in Specific Conductance section
- `VerificationDate24` in Specific Conductance section
- `ADVMRecordStart24` in ADVM section
- `ADVMRecordEnd24` in ADVM section
- `TemperatureMeasureDate24` in Temperature section
- `DischargeRecordStart24` in Discharge section
- `DischargeRecordEnd24` in Discharge section
- `ADVMDischarge_RecordStart24` in Discharge section
- `ADVMDischarge_RecordEnd24` in Discharge section
- `DataLoggerRecordStart24` in Logger File section
- `DataLoggerRecordEnd24` in Logger File section
- `BatteryReplacementDate224` in Logger File section
- `DataLoggerTime224` in Logger File section
- `DataLoggerTimeActual224` in Logger File section
- `DataLoggerTimeAdjDate224` in Logger File section

**Comment by mmannion** [comment]
Per team meeting discussion, cannot enter 24 hour format in Survey input box (tested)

**Comment by mripp** [comment]
During meeting on 4/1
We confirmed that if the Windows 11 Region setting is set to a local that uses 24 hour time then the Survey123 field application automatically utilizes 24 time formatting. 

Example of Setting
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/8e62e2e9-8849-4cf5-974e-4f38f8c9cce9)

**Comment by mmannion** [comment]
Attaching summary email from @rkircher about causes > options for time format issue.

[email.pdf](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/14825996/email.pdf)

**Comment by mmannion** [comment]
@kprice-TLH @Bikechain will investigate Windows 11 locale settings. More options than Windows 10, and field laptops in the process of being updated.

**Comment by mmannion** [comment]
On Windows 11:
- Use UK locale
- Fixes 24-hour format in Survey123
- Dates remain as "Monday, 1 April 2024"
  - Don't anticipate problem because month is spelled out
