### ISSUE TITLE
Order MeasuringPoints by Most Used (ENH-000158597)

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#86]
# Requirements

When the user pulls up the survey the Measuring Point in the 1st position is the location that gets used most frequently

# Persisting Display Order

We desire to control the display order of Measuring Points in the Survey123 and, optionally, Field Maps geodatabase clients. The Aquarius application / users does not have this requirement and, in turn, does not have an attribute for sorting Measuring Points. Alternatives such as embedding the display order as a prefix in the Measuring Point name, or adding a tagged display order property to the free-form text description are unpalatable.

Accordingly, the system-of-record for Measuring Point display order should be the geodatabase.

The existing model supports storing this information in the `MeasuringPoint.DisplayOrder` attribute. We need a workflow for preserving these values when updating the geodatabase, both during:

- Testing, when overwriting the entire database with fresh data from Aquarius
- Production, when performing incremental updates from Aquarius to the geodatabase

The production update workflow still needs to be designed.

For now, during testing, we should preserve a copy of the `MeasuringPoint` table _outside the `hydro` geodatabase_ (which will be dropped during update). Upon subsequent update, we can transfer the prior `DisplayOrder` values to the updated `MeasuringPoint` table by joining it to the copied table on the `AquariusID` attribute.

# To Do

- [x] @kprice-TLH will determine if there is a field for Measuring Point that is already recorded that describes if the MP is most used. ~For example: MPs with the most recent activation date would be ordered first.~
  - Create "rank" column with human-assigned value
- ~@craignwf add Measuring Point sort order column to `Reference_Points.csv` export file~
- [x] @mmannion add sort column to `MeasuringPoint` table
- [ ] @mmannion update data loader to retain display order when updating data (see _Persisting Display Order_ above)
- ~@mmannion will sort the MeasuringPoint table based on this field~
- [ ] ~@mripp to research option to order by via bind::esri:parameters [see](https://community.esri.com/t5/arcgis-survey123-questions/prevent-overwriting-existing-repeats/m-p/876559#M29414)
- [x] @rkircher  create enhancement request to add sorting support in Survey123

**Comment by mmannion** [comment]
Database requires that client (Survey) determines sort order (`ORDER BY`). Need to figure out how to pass `ORDER BY` clause from Survey.

**Comment by mmannion** [comment]
- Added `MeasuringPoint.DisplayOrder` column
- Updated data model diagram
- Added stub to data loader
  - Awaiting source data

**Comment by mripp** [comment]
Based on email correspondence with James Tedrick on April 17, 2023. There isn't a parameter in Survey123 to order the records queried from an Inbox. 

Based on this information I think we should talk about terminated this tasks. If there isn't a way to sort in the database and their isn't a way to sort in Survey123 this will not be possible.

**Comment by mmannion** [comment]
Per team meeting, do back-end work and file enhancement request for order by support

**Comment by SarahNWF** [comment]
Morgan to look into how measuring points are being ordered 
How to customize order or radio buttons

**Comment by mripp** [comment]
On next call Morgan to demo how Measuring Points are shown in Applications

Example: 008099, **008481**

**FieldMaps** ordered by OBJECTID
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/6b7299a5-98cb-4dcc-932b-fdbca493f098)

**Survey123**
Shown under Inventory Section, ordered by OBJECTID by default
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/f0ff05c3-2116-4eb5-8c43-1188ed5679d5)

Shown in the Stage, and Groundwater section, can be ordered by OrderBy field since it comes from the external CSV
![Image](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/assets/55856222/1d54ad2f-8a89-4a73-a515-d11c18db8d65)

**Comment by mripp** [comment]
Discussed on 8/14
- It is important to have Survey123 Inventory table ordered
- It is important to have the Survey123 MP radio buttons ordered
- It is less important to have the Field Maps MPs ordered

**Comment by mripp** [comment]
ENH is still under review. I emailed the tech support representative since they never responded from a previous email

**Comment by mmannion** [comment]
Per 2024-05-13 team meeting:
- Field user will know which MP to use
- Good naming / descriptions will allow them to identify the right choice in the survey
Therefore, this would be nice to have, but not critical. Moving to _Rejected_.
