### ISSUE TITLE
Refine low battery conditions

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#89]
Batteries are currently considered low when:
- <12.45V for data logger
- <12.6V for ADVM

There are other conditions, like:
- Loggers powered by AA (~5V)
- Loggers that report battery by percent
  - Note these batteries can't be replaced
  - Equipment must be replaced when the battery dies, or switch to external power

Goal is still for survey to prompt user to replace when low

Tasks are:

- [x] @mmannion Update model to include voltage cutoff per logger type
- [x] @mmannion Update data loader to populate voltage cutoff based on logger type
- [x] @kprice-TLH Send list of logger models and their cutoff voltages
- [x] @mripp Update survey to prompt based on logger-specific low voltage condition

**Comment by kprice-TLH** [comment]
when "Type of Recorder" = Ott Orpheus Mini, voltage cut off is 4.2
when "Type of Recorder" = In-Situ Level Troll 500 or In-Situ Level Troll 700 voltage is expressed in %, there is no cut off, but a warning of low battery should be given at 40%
* In-Situ Level Trolls can be used as an integrated logger (logger and sensor in one as above) or only  as a sensor connected to a separate logger, as a sensor connected to a logger, it will not have a separate voltage from the logger

**Comment by mmannion** [comment]
Team meeting notes:
- For "In-Situ Level Troll" loggers, can't replace battery
- Notify user to pay attention to unexpected logger behavior starting at 40%
- User doesn't need to take any action

**Comment by mmannion** [comment]
- Added `DataLogger.LowVoltage` column
- Updated data loader with low voltages documented in prior comments

Note that ADVM is not a "Data Logger" per our model, so their voltages are still hardwired to 12.6 for all models, per original requirements.
