### ISSUE TITLE
Update Reserved Words in Data Model

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#9]
'Name' and 'Comment' field in the Location table need to be updated since it is a reserved word in Survey123

[Reserved Words.xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/9537677/Reserved.Words.xlsx)

**Comment by mripp** [comment]
'Name' and 'Comment' field in the Location table need to be updated since it is a reserved word in Survey123

[Reserved Words.xlsx](https://github.com/NWFWMD-IT/Hydrologic-Monitoring-Project/files/9537677/Reserved.Words.xlsx)

**Comment by mmannion** [comment]
@mripp:

1. Is the column name `Comments`, with an "s" on the end, causing trouble with the Survey configuration? The attached spreadsheet lists "COMMENT", singular, as a reserved word, but not "COMMENTS" plural.
1. Likewise, is `Name` problematic? The attachment includes many keywords with the string "NAME" within them (e.g. CATALOG_NAME), but "NAME" itself is not listed as a keyword.

**Comment by mripp** [comment]
@mmannion  - You can close this out without changing the Comment or Name fields.

These were causing an issue because Name and Comment appear multiple times throughout different tables in the model so the survey was confused which field I was referring to. 

This is fixed because of the way I am publishing the feature services now.

**Comment by mmannion** [comment]
Appears to be the same issue as #12. See that issue for more information.
