### ISSUE TITLE
Updated Real Time Data Logger Field Calculation

### ISSUE THREAD

**Issue by mripp** [NWFWMD-IT/Hydrologic-Monitoring-Project#91]
For Stage, Groundwater, Conductivity, ADVM, and Temperature

I updated the survey to prepopulate the question based on if the location HasDataLogger or if the battery was not replaced because of DOA. 
Previously I was just looking at the HasDataLogger field and not the replacement field 
In addition, I made this field editable in case the user wants to overwrite the value. 

![Image](https://user-images.githubusercontent.com/55856222/232101778-ee71b2f3-8534-4d3a-b213-e09dff82f30c.png)

Question: What would Katie and Steve like to see this question appear as? Right now it reads "Data Logger Available to Measure Real-Time Level?

![Image](https://user-images.githubusercontent.com/55856222/232102528-2a684b65-956b-494f-862c-98d83f3b3505.png)

**Comment by mmannion** [comment]
Confirmed solution above in 2023-04-17 meeting
