### ISSUE TITLE
Add domain value for low In-Situ logger battery behavior

### ISSUE THREAD

**Issue by mmannion** [NWFWMD-IT/Hydrologic-Monitoring-Project#93]
If In-Situ logger battery level is low, behavior may get weird. In this case, need to communicate weirdness to back office. Do this as a Location Issue.

Determine for _Location Issue Type_ domain whether:
- Use existing "Other" domain value + comments
- Add new domain value

**Comment by kprice-TLH** [comment]
new domain added in version 20230724 of domains
see #24
